<a href="https://colab.research.google.com/github/mudit573/codeinnovationseries-poornima/blob/main/MUDIT_MATHUR_ML_Lab_MT1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from google.colab import files
uploaded = files.upload()

Saving Classification Dataset2.csv - Classification Dataset2.csv.csv to Classification Dataset2.csv - Classification Dataset2.csv (1).csv


In [76]:
dataset = pd.read_csv('Classification Dataset2.csv - Classification Dataset2.csv.csv')
print(dataset)

     Gender  Glucose    BP  SkinThickness  ...   BMI  PedigreeFunction  Age  Outcome
0      Male      148  72.0           35.0  ...  33.6             0.627   50        1
1    Female       85  66.0           29.0  ...  26.6             0.351   31        0
2    Female      183  64.0            0.0  ...  23.3             0.672   32        1
3    Female       89  66.0           23.0  ...  28.1             0.167   21        0
4      Male      137   NaN           35.0  ...  43.1             2.288   33        1
..      ...      ...   ...            ...  ...   ...               ...  ...      ...
559    Male       85  74.0            0.0  ...  30.1             0.300   35        0
560    Male      125  76.0            0.0  ...  33.8             0.121   54        1
561    Male      198  66.0           32.0  ...  41.3             0.502   28        1
562    Male       87  68.0           34.0  ...  37.6             0.401   24        0
563    Male       99  60.0           19.0  ...  26.9             

In [77]:
print(dataset.info())


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 564 entries, 0 to 563
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Gender            564 non-null    object 
 1   Glucose           564 non-null    int64  
 2   BP                548 non-null    float64
 3   SkinThickness     553 non-null    float64
 4   Insulin           552 non-null    float64
 5   BMI               547 non-null    float64
 6   PedigreeFunction  546 non-null    float64
 7   Age               564 non-null    int64  
 8   Outcome           564 non-null    int64  
dtypes: float64(5), int64(3), object(1)
memory usage: 39.8+ KB
None


In [78]:
types = dataset.dtypes
print(types)


Gender               object
Glucose               int64
BP                  float64
SkinThickness       float64
Insulin             float64
BMI                 float64
PedigreeFunction    float64
Age                   int64
Outcome               int64
dtype: object


In [79]:
dataset.isnull().sum()

Gender               0
Glucose              0
BP                  16
SkinThickness       11
Insulin             12
BMI                 17
PedigreeFunction    18
Age                  0
Outcome              0
dtype: int64

In [160]:
from sklearn.preprocessing import LabelEncoder
labelencoder_x = LabelEncoder()
x[:, 0] = labelencoder_x.fit_transform(x[:,0])

In [161]:
print(x)

[[1 148 72.0]
 [0 85 66.0]
 [0 183 64.0]
 ...
 [1 198 66.0]
 [1 87 68.0]
 [1 99 60.0]]


In [162]:
from sklearn.impute import SimpleImputer
x = dataset.iloc[:,0:3].values
y = dataset.iloc[:, 3].values

In [163]:
print(x)

[['Male' 148 72.0]
 ['Female' 85 66.0]
 ['Female' 183 64.0]
 ...
 ['Male' 198 66.0]
 ['Male' 87 68.0]
 ['Male' 99 60.0]]


In [164]:
print(y)

[35. 29.  0. 23. 35.  0. 32.  0. 45.  0.  0.  0.  0. 23. 19.  0. 47.  0.
 38. 30. 41.  0.  0. 35. 33. 26.  0. 15. 19.  0. 26. 36. 11.  0. 31. 33.
  0. 37. 42. 47. 25.  0. 18. 24.  0. 39.  0. 27. 32.  0. 11. 15. 21. 34.
 42. 10. 39. 60.  0. 41.  0.  0.  0. 34. nan 27. 30.  0. 13. 27. 20. 35.
  0. 20. 30. 20.  0. 33.  0. nan 13.  0. 26. 28.  0. 29. 54. nan 32. 19.
  0. 15. 40. nan 18. 27. 28. 18. nan 51.  0. nan  0. 18.  0. 29.  0. 28.
 31. 25. 33. 26. 34.  0. 32.  0.  0.  0. 23. 15. 56. 39. 30.  0.  0. 42.
 30. 36. 24.  0. 14.  0. 37. 31. 13. 20. 26. 25.  0. 29.  0. 30. 26.  0.
 31. 23. 37. 35.  0. 17. 50.  0. 28. 42.  0. 44. 15. 21. 19. 41. 38. 40.
 34. 23.  0. 18. 25.  0.  0. 12.  0. 23. 23. 42. 24. 42.  0. 46.  0.  0.
  0. 18. 20.  0.  0. 28. 36. 41. 39. 35.  0. 44.  0.  0. 20. 41.  0. 13.
 44. 27. 16.  0. 20. 16. 32. 28. 29.  0. 27. 33. 22. 54. 31. 26. 32. 40.
 41. 30. 22.  0. 29.  0.  0. 33. 15. 27.  0. 38. 39. 31.  0. 37. 25.  0.
 28.  0. 21. 27. 21.  0. 24. 32.  0. 22. 35. 15.  0

In [139]:
print(x.shape)
print(x)

(564, 3)
[['Male' 148 72.0]
 ['Female' 85 66.0]
 ['Female' 183 64.0]
 ...
 ['Male' 198 66.0]
 ['Male' 87 68.0]
 ['Male' 99 60.0]]


In [140]:
dataset.isnull().sum()


Gender               0
Glucose              0
BP                  16
SkinThickness       11
Insulin             12
BMI                 17
PedigreeFunction    18
Age                  0
Outcome              0
dtype: int64

In [142]:
print(x)

[['Male' 148 72.0]
 ['Female' 85 66.0]
 ['Female' 183 64.0]
 ...
 ['Male' 198 66.0]
 ['Male' 87 68.0]
 ['Male' 99 60.0]]


In [119]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 42)

In [143]:
print(x_train)

[['Male' 95 60.0]
 ['Female' 83 58.0]
 ['Male' 197 70.0]
 ...
 ['Male' 101 86.0]
 ['Male' 141 0.0]
 ['Male' 125 96.0]]


In [144]:
print(y_train)

[18. 31. 39. 19.  0. 29. 40.  0. 39. 32. 27.  0. 27.  0. 23. 29. 17. 17.
  0. 35. 20. 18. 27.  0. 41. 22.  0. 25. 32. 30.  0. 22. 13. 30. 23.  0.
 39. 37.  0. 31.  8. 18.  0.  0. 26. 32. 32. 33. 18. 16. 11.  0.  0. 38.
  0. 30.  0. nan  0. 24. 36.  0. 35. 42.  0.  0. 60.  0. 33.  0.  0. 30.
  0. 33. 37. 32. 28. 38. 38. 18.  0.  0. 40. 35. 21.  0.  0.  0.  0. 39.
 29. nan 35. 43. 47. 32. 15. 16. 23. 32. 25.  0.  0. 18. 23. 33. 29.  0.
  0. 15. 27. 23.  0.  0. 18. 11. 31. 37. 21. 27. 37. 42. 23. 43. 20. 12.
  0. nan  0. 39. 34.  0. 28. 43. 25.  0. 22. 18. 27. 30. 40. 25. 15. 21.
  0. 46. 30. 17. 41. 30. 40.  0.  0. 29. 32.  0. 41. 26. 12. 49. 32. 34.
 29. 50.  0. 22. 42. 30. 14. 44. nan 37. 27. 35. 23. 19.  0. 18. 28.  0.
  0.  0. 18.  0. 45. 32. 30.  0. 20. 33.  0. 28.  0. 39. 37. 19. 41. 42.
 28. 33. 18.  0.  0. 26. 19. 34.  0. 28. 25.  0.  0.  0.  0. 17. 34.  0.
 30.  0.  0. 31.  0.  8.  0. 23. 15.  0.  0. 26. 13. 46. 16. 25.  0. 56.
 18. 15. 38. 32.  0. 36. 23. 26.  7.  0. 28. 45. 12

In [145]:
print(x_test)

[['Male' 57 60.0]
 ['Female' 114 0.0]
 ['Male' 74 68.0]
 ['Male' 130 70.0]
 ['Male' 135 68.0]
 ['Female' 115 66.0]
 ['Female' 165 90.0]
 ['Male' 166 74.0]
 ['Female' 100 66.0]
 ['Male' 119 0.0]
 ['Female' 83 78.0]
 ['Female' 147 78.0]
 ['Female' 113 64.0]
 ['Male' 158 84.0]
 ['Male' 97 68.0]
 ['Female' 153 82.0]
 ['Male' 146 70.0]
 ['Male' 104 64.0]
 ['Male' 107 76.0]
 ['Male' 122 56.0]
 ['Female' 102 75.0]
 ['Female' 85 78.0]
 ['Male' 184 84.0]
 ['Female' 111 86.0]
 ['Male' 86 68.0]
 ['Male' 104 74.0]
 ['Female' 110 nan]
 ['Female' 95 85.0]
 ['Female' 81 60.0]
 ['Female' 106 52.0]
 ['Male' 187 76.0]
 ['Female' 100 66.0]
 ['Female' 78 50.0]
 ['Female' 80 55.0]
 ['Male' 116 70.0]
 ['Male' 132 0.0]
 ['Male' 62 78.0]
 ['Female' 101 65.0]
 ['Female' 88 74.0]
 ['Female' 124 70.0]
 ['Male' 124 70.0]
 ['Male' 173 84.0]
 ['Male' 85 65.0]
 ['Female' 61 82.0]
 ['Female' 109 75.0]
 ['Female' 73 50.0]
 ['Male' 100 74.0]
 ['Female' 147 74.0]
 ['Female' 125 70.0]
 ['Male' 129 nan]
 ['Male' 128 78.0]

In [146]:
print(y_test)

[ 0.  0. 28. nan 42. 39. 33.  0. 29.  0. 26.  0. 35. 41. 21. 42.  0. 37.
  0.  0. 23.  0. 33. 19. 28. 18.  0. 25. 22.  0. 27. 20. 32.  0. 28.  0.
  0. 28. 19. 33. 20. 33.  0. 28. 26. 10. 40. 25. 24. 20.  0. 47.  0.  0.
  0. 32. 40. 37. 37. 37.  0. 37. 21. 36. 23.  0. 17. 38. 16.  0. 30.  0.
 39. 41. 18. nan  0. 32. 54.  0. 43. 15. 22. 35. 52. 19. 26.  0. 23. nan
 33. 33. 46. 44. 32.  0. 28. 20. 30. 13.  0. 13. 44. 34. 31. 24.  0. 11.
  0. 32. 33. 48.  0. 16.  0. 54. 35. 12.  0. 30.  0.  0. 22. 34. 30. 19.
 25.  0.  0. 38. 13.  0. 25. 32. 32.  0. 12. 42.  0.  0. nan]


In [147]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test)

ValueError: ignored

In [148]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state =35)
classifier.fit(x_train, y_train)

ValueError: ignored

In [149]:
y_pred = classifier.predict(x_test)
print(y_pred)

NotFittedError: ignored